---
title: "UVRIseq NGS-based HIVDR report"
author: "Generated by: "
date: "Date: `r Sys.Date()`"
params:
  dr_report_hydra: ""
  dr_report_hivdb: ""
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    #vertical_layout: fill
    vertical_layout: scroll
    theme: flatly #spacelab
    #runtime: shiny
---

```{r setup, include=FALSE}
require(knitr)
library(flexdashboard)
require(tidyverse)
#require(shiny)
```

```{r, eval=TRUE}
generate_dr_report<-function(path){
  hivdr <- jsonlite::fromJSON(path, flatten = TRUE)
tmp<-data.frame()
for (i in 1:dim(hivdr)[1]) {
  seq_df <- hivdr[i,]
  seq<-seq_df$inputSequence.header
  drug_res<-seq_df$drugResistance[[1]]
  genes<-drug_res$gene.name
  for (gene in unique(genes)) {
    gene_df<-drug_res[drug_res$gene.name==gene,]
    gene_drug_scores<-gene_df$drugScores[[1]]
    gene_drug_scores<-gene_drug_scores[c("drugClass.name","drug.name", "score", "text")]
    tmp<-rbind(tmp, gene_drug_scores)
    }
  names(tmp)<-c("drugClass.name", "Drug name", "HIVDB Score", "Drug susceptibility")
  mutations<-seq_df$alignedGeneSequences[[1]]$mutations[[1]]
  mutation_list<-paste0(mutations$consensus,mutations$position,mutations$AAs)
}
out<-list(seq=seq, genes=genes, drugscores=tmp, mutations=mutation_list)
return(out)
}
```

```{r}
hivdr<-generate_dr_report(params$dr_report_hivdb)
seq<-hivdr$seq
genes<-hivdr$genes
mutation_list<-hivdr$mutation_list
tmp<-hivdr$drugscores
```

```{r}
dr_report<-read.csv(params$dr_report_hydra)
dr_report$variants<-paste0(dr_report$Wildtype,
                           dr_report$Position,
                           dr_report$Mutation)

PR<-dr_report[dr_report$Gene=="PR",]
PR_minor_mutations<-PR$variants[PR$Category=="PIMinor"]
PR_major_mutations<-PR$variants[PR$Category=="PIMajor"]

RT<-dr_report[dr_report$Gene=="RT",]
NNRTI_mutations<-RT$variants[RT$Category=="NNRTI"]
NRTI_mutations<-RT$variants[RT$Category=="NRTI"]
OTHER_mutations<-RT$variants[RT$Category=="Other"]

IN<-dr_report[dr_report$Gene=="IN",]
IN_accessory_mutations<-IN$variants[IN$Category=="Accessory"]
IN_major_mutations<-IN$variants[IN$Category=="Major"]
```

<!-- Column {.sidebar data-width=300} -->
<!-- ------------------------------------- -->

<!-- ```{r} -->
<!-- #selectInput("sequence", label = "Select Consensus Sequence:", choices = seq) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- #selectInput("threshold", label = "Select Mutational Threshold:", choices = c("20%","10%","5%","2%","1%", "0.5%", "0.2%", "0.1%")) -->
<!-- ``` -->

<!-- Credits: Quasitools, Hydra, Sierralocal, HIVdb. -->

Row 1
-----------------------------------------------------------------------

### Sequence summary

Query ID: `r seq`

Sequence includes: `r genes`

Sequence subtype: Unknown

Mutation threshold: 20%

<!-- Mutations: `r hivdr$mutations` -->

Row 2
-----------------------------------------------------------------------

### Drug Resistance Interpretation: PR

PI Major Mutations: `r PR_major_mutations`

PI Minor Mutations: `r PR_minor_mutations`

Other Mutations:

Comments:

### Mutation HIVDR Scores: PR

```{r}
PR_df<-tmp[tmp$drugClass.name=="PI",]
PR_df[2:4] %>% 
  knitr::kable(row.names=F, align = "c")
```

Row 3
-----------------------------------------------------------------------


### Drug Resistance Interpretation: RT

NNRTI Mutations: `r NNRTI_mutations`

NRTI Mutations: `r NRTI_mutations`

Other Mutations: `r OTHER_mutations`

Comments:

### Mutation HIVDR Scores: NNRTI

```{r}
RT_df<-tmp[tmp$drugClass.name=="NNRTI",]
RT_df[2:4] %>% 
  knitr::kable(row.names=F, align = "c")
```

### Mutation HIVDR Scores: NRTI

```{r}
RT_df<-tmp[tmp$drugClass.name=="NRTI",]
RT_df[2:4] %>% 
  knitr::kable(row.names=F, align = "c")
```

Row 4
-----------------------------------------------------------------------


### Drug Resistance Interpretation: INI

INI Major Mutations: `r IN_major_mutations`

INI Accessory Mutations: `r IN_accessory_mutations`

Other Mutations:

Comments:

### Mutation HIVDR Scores: INI
```{r}
IN_df<-tmp[tmp$drugClass.name=="INSTI",]
IN_df[2:4] %>% 
  knitr::kable(row.names=F, align = "c")
```
